{% set name = "mfem" %}
{% set version = "4.5.2" %}
{% set build = 0 %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mfem/mfem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9431d72a2834078f25c58430767bf2fd62bf43a0feb003189a86847c68b8af4a

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage("mfem", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ mpi }}  # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - {{ mpi }}
    - hypre
    - metis
  run:
    - {{ mpi }}
    - hypre
    - metis

test:
  commands:
    - test -f $PREFIX/lib/libmfem${SHLIB_EXT}

about:
  home: https://mfem.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Lightweight, general, scalable C++ library for finite element methods
  description: |
    MFEM is a modular parallel C++ library for finite element methods. Its goal is
    to enable high-performance scalable finite element discretization research and
    application development on a wide variety of platforms, ranging from laptops to
    supercomputers.
  doc_url: https://mfem.org/serial-tutorial/
  dev_url: https://github.com/mfem/mfem

extra:
  recipe-maintainers:
    - matthiasdiener
